// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeteringApplicationAPI.Migrations
{
    [DbContext(typeof(SmartMeteringDbContext))]
    [Migration("20260621210000_DropOznakaBrojilaColumn")]
    partial class DropOznakaBrojilaColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Objekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Objekti");
                });

            modelBuilder.Entity("PametnoBrojilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaksimalnaOdobrenaSnaga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjekatId")
                        .HasColumnType("int");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ObjekatId");

                    b.HasIndex("SerijskiBroj")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasFilter("[Uuid] IS NOT NULL");

                    b.ToTable("PametnaBrojila");
                });

            modelBuilder.Entity("Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojiloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergijaNT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EnergijaVT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FiksniTroskovi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GodinaObracuna")
                        .HasColumnType("int");

                    b.Property<decimal>("IznosCrvena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosPlava")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosZelena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("MesecObracuna")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekstRacuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrojiloId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("TarifniModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaC_NT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaC_VT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaObracunskeSnage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaP_NT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaP_VT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaZ_NT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CenaZ_VT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAktivan")
                        .HasColumnType("bit");

                    b.Property<decimal>("TrosakSnabdevaca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TarifniModeli");
                });

            modelBuilder.Entity("Objekat", b =>
                {
                    b.HasOne("Korisnik", "Korisnik")
                        .WithMany("Objekti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PametnoBrojilo", b =>
                {
                    b.HasOne("Objekat", "Objekat")
                        .WithMany("PametnaBrojila")
                        .HasForeignKey("ObjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objekat");
                });

            modelBuilder.Entity("Racun", b =>
                {
                    b.HasOne("PametnoBrojilo", "Brojilo")
                        .WithMany()
                        .HasForeignKey("BrojiloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brojilo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Korisnik", b =>
                {
                    b.Navigation("Objekti");
                });

            modelBuilder.Entity("Objekat", b =>
                {
                    b.Navigation("PametnaBrojila");
                });
#pragma warning restore 612, 618
        }
    }
}
